---
- import_tasks: sensu_pre.yml
- import_tasks: sensu_install.yml

- block: # Config sensu
  - import_tasks: sensu_search_config.yml
  - import_tasks: sensu_post.yml
  tags:
    - sensu-config

- import_tasks: sensu_install_plugin.yml
  tags:
    - sensu-install-plugin
    - sensu-plugin
