---
- name: Copy sensu configuration file
  synchronize:
    src: "{{ sensu_host_config_path }}/"
    dest: "{{ sensu_config_base_path }}/"
    delete: yes
    rsync_opts:
      - "--exclude=ssl"
  when: sensu_config_check.stat.exists
  notify: 
    - Restart sensu server
    - Restart sensu api
    - Restart sensu client

- name: Copy SSL certificates directory
  copy:
    src: "{{ sensu_host_config_path }}/ssl"
    dest: "{{ sensu_config_path }}/"
  when:
    - sensu_config_ssl_check.stat.isdir is defined
    - sensu_config_ssl_check.stat.isdir
  notify: 
    - Restart sensu server
    - Restart sensu api
    - Restart sensu client


- block: # Dynamic configuration style
  - name: Combine dict sensu_handler and sensu_handler_plugins
    set_fact:
      sensu_handlers_combined: "{{ { 'handlers': sensu_handlers } | combine(sensu_handler_plugins) }}"
    when: not sensu_config_check.stat.exists

  - name: Drop sensu configuration file(s)
    template:
      src: config.json.j2
      dest: "{{ sensu_config_file_path }}"
    when: not sensu_config_check.stat.exists
    notify: 
      - Restart sensu server
      - Restart sensu api
      - Restart sensu client

- meta: flush_handlers