---
- name: Add sensu repository key
  apt_key:
    url: "{{ sensu_apt_key_url }}"
    state: present

- name: Install sensu apt repository
  apt_repository:
    repo: "{{ sensu_deb_url }}"
    state: present