---
- name: Copy sensu configuration file
  template:
    src: "{{ sensu_host_config_file_path }}"
    dest: "{{ sensu_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: sensu_config_check.stat.exists
  notify: Restart {{ sensu_server_service_name }}