---
- name: Install sensu and dependencies packages
  apt:
    name: "{{ sensu_apt_dependencies + sensu_apt_package }}"
    state: present
    update_cache: yes

- name: Ensure Sensu stay on "Server" mode only
  systemd:
    name: "{{ sensu_client_service_name }}"
    state: stopped
    enabled: no
  when: 
    - sensu_api
    - sensu_redis
    - sensu_rabbitmq
    - not sensu_client

- name: Ensure Sensu stay on "Client" mode only
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - "{{ sensu_server_service_name }}"
    - "{{ sensu_api_service_name }}"
  when:
    - not sensu_api
    - not sensu_redis
    - sensu_rabbitmq
    - sensu_client
