---
- name: Restart {{ sensu_server_service_name }}
  service:
    name: {{ sensu_server_service_name }}
    state: restarted

- name: Restart sensu-api
  service:
    name: sensu-api
    state: restarted

- name: Restart sensu-client
  service:
    name: sensu-client
    state: restarted