---
- name: Restart sensu server
  systemd:
    name: "{{ sensu_server_service_name }}"
    state: restarted
    enabled: yes
  when:
    - sensu_api
    - sensu_redis
    - sensu_rabbitmq

- name: Restart sensu api
  systemd:
    name: "{{ sensu_api_service_name }}"
    state: restarted
    enabled: yes
  when:
    - sensu_api
    - sensu_redis
    - sensu_rabbitmq

- name: Restart sensu client
  systemd:
    name: "{{ sensu_client_service_name }}"
    state: restarted
    enabled: yes
  when:
    - sensu_rabbitmq
    - sensu_client
